# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:21.0.1
  amd64: ghcr.io/hassio-addons/base:21.0.1

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: CarConnectivity"
  org.opencontainers.image.description: "Addon version of Carconnectivity made by Till (see https://github.com/tillsteinbach/CarConnectivity) throught MQTT"
  org.opencontainers.image.source: "https://github.com/Pulpyyyy/carconnectivity-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"

args:
  AUDI_VERSION: "v0.3.2"
  SKODA_VERSION: "v0.12.6"
  VW_COMMIT: "4906c58892e67a2c85ffc3574e8c816057a7cbba"
  VWNA_VERSION: "v0.1.25"
  VWEUDATA_VERSION: "v0.3.0"
  RENAULTDACIA_VERSION: "v0.1a1"
  TRONITY_VERSION: "v0.7.3"
  VOLVO_VERSION: "v0.1a2"
  ABRP_VERSION: "v0.8.3"
  MQTT_VERSION: "v0.10.5.post1"
  MQTTHA_VERSION: "v0.6.6"
  WEBUI_VERSION: "v0.7.3"
  CC_VERSION: "v0.11.10"